-- GhostRegistry upgrade columns/tables for the newer dashboard, profile pictures, shop equip, wheels, chat, and checks.
-- Paste this into Supabase SQL Editor if the System Check page says columns/tables are missing.

alter table if exists users add column if not exists credits integer default 50;
alter table if exists users add column if not exists social_code text;
alter table if exists users add column if not exists rank text;
alter table if exists users add column if not exists session_version integer default 1;
alter table if exists users add column if not exists account_locked boolean default false;
alter table if exists users add column if not exists last_spin text;
alter table if exists users add column if not exists last_elite_spin text;
alter table if exists users add column if not exists elite_wheel boolean default false;
alter table if exists users add column if not exists profile_effect text default '';
alter table if exists users add column if not exists avatar_url text default '';
alter table if exists users add column if not exists banner_url text default '';
alter table if exists users add column if not exists bio text default '';

create table if not exists user_inventory (
    id bigint generated by default as identity primary key,
    user_id bigint,
    item_name text,
    item_key text,
    item_type text default 'general',
    quantity integer default 1,
    meta jsonb default '{}'::jsonb,
    created_at timestamptz default now()
);

create table if not exists shop_purchases (
    id bigint generated by default as identity primary key,
    user_id bigint,
    item_name text,
    item_key text,
    cost integer default 0,
    reward_text text default '',
    created_at timestamptz default now()
);

create table if not exists record_unlocks (
    id bigint generated by default as identity primary key,
    user_id bigint,
    record_id bigint,
    created_at timestamptz default now(),
    unique(user_id, record_id)
);

create table if not exists credit_logs (
    id bigint generated by default as identity primary key,
    user_id bigint,
    username text,
    amount integer,
    action text,
    details text,
    created_at timestamptz default now()
);

create table if not exists chat_messages (
    id bigint generated by default as identity primary key,
    user_id bigint,
    username text,
    social_code text,
    message text,
    created_at timestamptz default now()
);

create table if not exists audit_logs (
    id bigint generated by default as identity primary key,
    action text,
    target_record text,
    performed_by text,
    details text,
    timestamp timestamptz default now(),
    created_at timestamptz default now()
);

-- GhostRegistry v3 systems: lockdown, notifications, achievements, messages, cases, marketplace
create table if not exists system_settings (
  id bigint generated by default as identity primary key,
  setting_key text unique not null,
  setting_value text,
  created_at timestamp with time zone default now()
);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id bigint,
  title text,
  message text,
  is_read boolean default false,
  created_at timestamp with time zone default now()
);

create table if not exists user_achievements (
  id bigint generated by default as identity primary key,
  user_id bigint,
  achievement_code text,
  title text,
  reward integer default 0,
  created_at timestamp with time zone default now(),
  unique(user_id, achievement_code)
);

create table if not exists private_messages (
  id bigint generated by default as identity primary key,
  sender_id bigint,
  sender_username text,
  recipient_id bigint,
  recipient_username text,
  body text,
  is_read boolean default false,
  created_at timestamp with time zone default now()
);

create table if not exists case_files (
  id bigint generated by default as identity primary key,
  user_id bigint,
  title text,
  notes text,
  record_ids text,
  created_at timestamp with time zone default now()
);

create table if not exists marketplace_listings (
  id bigint generated by default as identity primary key,
  seller_id bigint,
  seller_username text,
  buyer_id bigint,
  item_name text,
  price integer default 0,
  status text default 'open',
  created_at timestamp with time zone default now()
);

insert into system_settings (setting_key, setting_value)
values ('website_lockdown', 'off')
on conflict (setting_key) do nothing;

-- v4 profile polish
alter table if exists users add column if not exists banner_url text default '';
alter table if exists users add column if not exists bio text default '';

-- =========================================================
-- v5 Ultimate Roadmap Additions
-- Safe columns/tables for roadmap, social icons, HQ, games, and noodle joke systems.
-- =========================================================

alter table users add column if not exists bio text default '';
alter table users add column if not exists banner_url text default '';
alter table users add column if not exists avatar_url text default '';
alter table users add column if not exists level integer default 1;
alter table users add column if not exists xp integer default 0;
alter table users add column if not exists title text default '';
alter table users add column if not exists reputation integer default 0;
alter table users add column if not exists last_seen timestamp with time zone default now();

create table if not exists fun_game_scores (
  id bigserial primary key,
  user_id bigint,
  username text,
  game_name text,
  score integer default 0,
  meta jsonb default '{}'::jsonb,
  created_at timestamp with time zone default now()
);

create table if not exists ghostnet_posts (
  id bigserial primary key,
  user_id bigint,
  username text,
  body text,
  likes integer default 0,
  created_at timestamp with time zone default now()
);

create table if not exists user_headquarters (
  id bigserial primary key,
  user_id bigint,
  wallpaper text default 'blue_matrix',
  pet_key text default '',
  display_title text default '',
  trophy_slots jsonb default '[]'::jsonb,
  updated_at timestamp with time zone default now()
);

create table if not exists login_calendar_claims (
  id bigserial primary key,
  user_id bigint,
  claim_day integer,
  reward_text text,
  created_at timestamp with time zone default now()
);

create table if not exists hall_of_fame_entries (
  id bigserial primary key,
  category text,
  username text,
  value_text text,
  created_at timestamp with time zone default now()
);

create table if not exists world_events (
  id bigserial primary key,
  title text,
  description text,
  event_type text,
  is_active boolean default false,
  created_by text,
  created_at timestamp with time zone default now()
);

create table if not exists architect_notes (
  id bigserial primary key,
  created_by text,
  note text,
  created_at timestamp with time zone default now()
);

create table if not exists cosmetic_catalog (
  id bigserial primary key,
  item_key text unique,
  item_name text,
  item_type text,
  rarity text default 'common',
  css_class text default '',
  created_at timestamp with time zone default now()
);


-- V10 final roadmap support tables
create table if not exists auctions (id bigserial primary key, seller_id bigint, item_name text, current_bid integer default 0, status text default 'open', created_at timestamp default now());
create table if not exists user_trades (id bigserial primary key, from_user_id bigint, to_user_id bigint, offer text, status text default 'pending', created_at timestamp default now());
create table if not exists site_events (id bigserial primary key, title text, event_type text, reward_multiplier numeric default 1, active boolean default false, created_at timestamp default now());
create table if not exists user_titles (id bigserial primary key, user_id bigint, title text, equipped boolean default false, created_at timestamp default now());
create table if not exists ghost_pets (id bigserial primary key, user_id bigint, pet_name text, pet_type text, equipped boolean default false, created_at timestamp default now());
create table if not exists community_votes (id bigserial primary key, user_id bigint, topic text, vote text, created_at timestamp default now());
create table if not exists casino_replays (id bigserial primary key, user_id bigint, game text, replay_data jsonb, created_at timestamp default now());
create table if not exists feature_flags (id bigserial primary key, feature_key text unique, enabled boolean default false, notes text, created_at timestamp default now());
